"""
database.py
------------
Handles all SQLite database operations for the AI Chatbot.

Responsibilities:
    - Create the database and required tables automatically if they
      do not already exist.
    - Insert new conversation records (user message + bot response).
    - Retrieve conversation history.
    - Clear conversation history.

This module uses Python's built-in `sqlite3` library, so no extra
database driver is required.
"""

import sqlite3
import logging
from contextlib import contextmanager
from datetime import datetime

logger = logging.getLogger(__name__)


class Database:
    """Wrapper around SQLite operations for chatbot conversations."""

    def __init__(self, db_path: str):
        """
        Initialize the Database object and ensure tables exist.

        Args:
            db_path (str): Path to the SQLite database file.
        """
        self.db_path = db_path
        self._create_tables()

    @contextmanager
    def _get_connection(self):
        """
        Context manager that yields a SQLite connection and guarantees
        it is closed afterwards, even if an exception occurs.
        """
        conn = sqlite3.connect(self.db_path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except sqlite3.Error as error:
            conn.rollback()
            logger.error("Database error: %s", error)
            raise
        finally:
            conn.close()

    def _create_tables(self):
        """Create the conversations table if it does not already exist."""
        create_table_query = """
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                user_message TEXT NOT NULL,
                bot_response TEXT NOT NULL,
                intent TEXT,
                timestamp TEXT NOT NULL
            )
        """
        try:
            with self._get_connection() as conn:
                conn.execute(create_table_query)
            logger.info("Database initialized successfully at %s", self.db_path)
        except sqlite3.Error as error:
            logger.error("Failed to create database tables: %s", error)
            raise

    def save_conversation(self, session_id: str, user_message: str,
                           bot_response: str, intent: str = None) -> int:
        """
        Save a single conversation turn to the database.

        Args:
            session_id (str): Unique identifier for the chat session.
            user_message (str): The message sent by the user.
            bot_response (str): The response generated by the bot.
            intent (str, optional): The Dialogflow intent that was matched.

        Returns:
            int: The row id of the newly inserted record.
        """
        insert_query = """
            INSERT INTO conversations (session_id, user_message, bot_response, intent, timestamp)
            VALUES (?, ?, ?, ?, ?)
        """
        timestamp = datetime.utcnow().isoformat()
        try:
            with self._get_connection() as conn:
                cursor = conn.execute(
                    insert_query,
                    (session_id, user_message, bot_response, intent, timestamp),
                )
                return cursor.lastrowid
        except sqlite3.Error as error:
            logger.error("Failed to save conversation: %s", error)
            raise

    def get_history(self, session_id: str, limit: int = 50) -> list:
        """
        Retrieve conversation history for a given session, most recent last.

        Args:
            session_id (str): Unique identifier for the chat session.
            limit (int): Maximum number of records to return.

        Returns:
            list[dict]: List of conversation records.
        """
        select_query = """
            SELECT id, session_id, user_message, bot_response, intent, timestamp
            FROM conversations
            WHERE session_id = ?
            ORDER BY id DESC
            LIMIT ?
        """
        try:
            with self._get_connection() as conn:
                rows = conn.execute(select_query, (session_id, limit)).fetchall()
                history = [dict(row) for row in rows]
                history.reverse()
                return history
        except sqlite3.Error as error:
            logger.error("Failed to fetch history: %s", error)
            raise

    def clear_history(self, session_id: str) -> None:
        """
        Delete all conversation records for a given session.

        Args:
            session_id (str): Unique identifier for the chat session.
        """
        delete_query = "DELETE FROM conversations WHERE session_id = ?"
        try:
            with self._get_connection() as conn:
                conn.execute(delete_query, (session_id,))
            logger.info("Cleared chat history for session %s", session_id)
        except sqlite3.Error as error:
            logger.error("Failed to clear history: %s", error)
            raise

    def get_total_conversations(self) -> int:
        """Return the total number of stored conversation records."""
        try:
            with self._get_connection() as conn:
                row = conn.execute("SELECT COUNT(*) as count FROM conversations").fetchone()
                return row["count"] if row else 0
        except sqlite3.Error as error:
            logger.error("Failed to count conversations: %s", error)
            raise
